/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulatorediforzevettoriali;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import static java.awt.SystemColor.text;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author andrea.frati
 */
public class InterfacciaGrafica extends javax.swing.JFrame {

    private ArrayList<Vector> vectors = new ArrayList<>();
    private Vector vectorTemp = new Vector(0, 0, "a");
    private Vector fRis = new Vector(0, 0, "forza risultante");
    private double xRis = 0;
    private double yRis = 0;
    private double xObject;
    private double yObject;
    private double xCenter;
    private double yCenter;
    private boolean firstVec = true;
    
    private boolean firstPaint = true;
    boolean animationStarted = false;
    BufferedImage bi;
    Graphics2D big;
    Timer timer;
    ActionListener act;

    /**
     * Creates new form InterfacciaGrafica
     */
    public InterfacciaGrafica() {
        initComponents();
        allInvisible();
        backButton.setVisible(false);
        createButton.setVisible(false);
        vectors.add(fRis);
    }
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        bi = new BufferedImage(canvasPanel.getWidth(), canvasPanel.getHeight(), BufferedImage.TYPE_INT_ARGB);
        big = bi.createGraphics();
        big.setStroke(new BasicStroke(0.8f));
        big.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        big.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        xCenter = (canvasPanel.getX() + canvasPanel.getWidth()) / 2;
        yCenter = (canvasPanel.getY() + canvasPanel.getHeight()) / 2;
        if(firstPaint){
            firstPaint = false;
            xObject = xCenter;
            yObject = yCenter;
        }
        big.setColor(Color.RED);
        for (int i = 0; i < vectors.size(); i++) {
            big.draw(new Line2D.Double(xObject, yObject, (int) vectors.get(i).x + xObject, (int) vectors.get(i).y + yObject));
            big.setColor(vectors.get(i).colore);
            
        }
        if (drag) {
            big.setColor(Color.BLACK);
            big.draw(new Line2D.Double(x, y, (int) vectorTemp.x, (int) vectorTemp.y));
        }
        //big.setColor(Color.BLUE);
        big.draw(new Line2D.Double(xCenter, yCenter, xObject, yObject));
        big.setColor(Color.BLACK);
        big.fill(new Ellipse2D.Double(xObject - 10, yObject - 10, 20, 20));
        
        g2.drawImage(bi, 0, 0, this);
    }

    public void allVisible() {
        buttonColor.setVisible(true);
        angoloLabel.setVisible(true);
        forzaLabel.setVisible(true);
        xCoordLabel.setVisible(true);
        yCoordLabel.setVisible(true);
        nameLabel.setVisible(true);

        textColor.setVisible(true);
        textForza.setVisible(true);
        textAngolo.setVisible(true);
        textX1.setVisible(true);
        textY1.setVisible(true);
        textName.setVisible(true);
    }

    public void allInvisible() {
        buttonColor.setVisible(false);
        angoloLabel.setVisible(false);
        forzaLabel.setVisible(false);
        xCoordLabel.setVisible(false);
        yCoordLabel.setVisible(false);
        nameLabel.setVisible(false);

        textColor.setVisible(false);
        textForza.setVisible(false);
        textAngolo.setVisible(false);
        textX1.setVisible(false);
        textY1.setVisible(false);
        textName.setVisible(false);
    }

    public void setEmptyText() {
        textX1.setText("");
        textY1.setText("");
        textForza.setText("");
        textAngolo.setText("");
        textName.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlsPanel = new javax.swing.JPanel();
        vectorInputPanel = new javax.swing.JPanel();
        angoloLabel = new javax.swing.JLabel();
        forzaLabel = new javax.swing.JLabel();
        xCoordLabel = new javax.swing.JLabel();
        yCoordLabel = new javax.swing.JLabel();
        textAngolo = new javax.swing.JTextField();
        textForza = new javax.swing.JTextField();
        textX1 = new javax.swing.JTextField();
        textY1 = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        buttonColor = new javax.swing.JButton();
        textColor = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        vectorsScrollPane = new javax.swing.JScrollPane();
        vectorList = new javax.swing.JList<>();
        newVectorButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        canvasPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        startButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        controlsPanel.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                controlsPanelAncestorResized(evt);
            }
        });

        angoloLabel.setText("Angolo");

        forzaLabel.setText("Forza");

        xCoordLabel.setText("X");

        yCoordLabel.setText("Y");

        textAngolo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textAngoloPropertyChange(evt);
            }
        });

        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });
        textName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textNamePropertyChange(evt);
            }
        });

        nameLabel.setText("Nome");

        buttonColor.setText("color");
        buttonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColorActionPerformed(evt);
            }
        });

        textColor.setText("colore");

        javax.swing.GroupLayout vectorInputPanelLayout = new javax.swing.GroupLayout(vectorInputPanel);
        vectorInputPanel.setLayout(vectorInputPanelLayout);
        vectorInputPanelLayout.setHorizontalGroup(
            vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vectorInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(angoloLabel)
                    .addGroup(vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(xCoordLabel)
                        .addComponent(forzaLabel)
                        .addComponent(yCoordLabel))
                    .addComponent(textColor))
                .addGap(18, 18, 18)
                .addGroup(vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textAngolo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textForza, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textX1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textY1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonColor, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        vectorInputPanelLayout.setVerticalGroup(
            vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vectorInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAngolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angoloLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textForza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forzaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xCoordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yCoordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vectorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vectorInputPanelLayout.createSequentialGroup()
                        .addComponent(textColor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buttonColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        createButton.setText("CREATE");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jCheckBox1.setText("coordinate polari");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        vectorList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vectorListMouseClicked(evt);
            }
        });
        vectorList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vectorListKeyPressed(evt);
            }
        });
        vectorsScrollPane.setViewportView(vectorList);

        newVectorButton.setText("NUOVO VETTORE");
        newVectorButton.setFocusable(false);
        newVectorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newVectorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newVectorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVectorButtonActionPerformed(evt);
            }
        });

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        removeButton.setText("remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        applyButton.setText("apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlsPanelLayout = new javax.swing.GroupLayout(controlsPanel);
        controlsPanel.setLayout(controlsPanelLayout);
        controlsPanelLayout.setHorizontalGroup(
            controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlsPanelLayout.createSequentialGroup()
                        .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlsPanelLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(vectorInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(controlsPanelLayout.createSequentialGroup()
                        .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vectorsScrollPane)
                            .addGroup(controlsPanelLayout.createSequentialGroup()
                                .addComponent(newVectorButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(createButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(backButton)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(controlsPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(removeButton)
                .addGap(18, 18, 18)
                .addComponent(applyButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        controlsPanelLayout.setVerticalGroup(
            controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsPanelLayout.createSequentialGroup()
                .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeButton)
                    .addComponent(applyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vectorsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vectorInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newVectorButton)
                    .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(createButton)
                        .addComponent(backButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(controlsPanel, java.awt.BorderLayout.EAST);

        canvasPanel.setBackground(new java.awt.Color(255, 255, 255));
        canvasPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        canvasPanel.setForeground(new java.awt.Color(255, 255, 255));
        canvasPanel.setMinimumSize(new java.awt.Dimension(400, 400));
        canvasPanel.setPreferredSize(new java.awt.Dimension(400, 400));
        canvasPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                canvasPanelMouseDragged(evt);
            }
        });
        canvasPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                canvasPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canvasPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout canvasPanelLayout = new javax.swing.GroupLayout(canvasPanel);
        canvasPanel.setLayout(canvasPanelLayout);
        canvasPanelLayout.setHorizontalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        canvasPanelLayout.setVerticalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        getContentPane().add(canvasPanel, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(startButton);

        resetButton.setText("RESET");
        resetButton.setFocusable(false);
        resetButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(resetButton);

        stopButton.setText("STOP");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(stopButton);

        saveButton.setText("SAVE");
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(saveButton);

        importButton.setText("IMPORT");
        importButton.setFocusable(false);
        importButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        importButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(importButton);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String[] addVectorNames() {
        String[] vectorNames = new String[vectors.size() + 1];
        for (int i = 0; i < vectors.size(); i++) {
            vectorNames[i] = vectors.get(i).getName();
        }
        return vectorNames;
    }
    private void newVectorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVectorButtonActionPerformed
        allVisible();
        setEmptyText();
        repaint();
        createButton.setVisible(true);
        if (jCheckBox1.isSelected()) {
            textX1.setVisible(false);
            textY1.setVisible(false);
        } else {
            textForza.setVisible(false);
            textAngolo.setVisible(false);
        }
        jCheckBox1.setEnabled(false);
        backButton.setVisible(true);
    }//GEN-LAST:event_newVectorButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

    }//GEN-LAST:event_jCheckBox1ActionPerformed
    public boolean isDouble(String str){
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String nameVar = textName.getText();
        /*int[] selected = vectorList.getSelectedIndices();
        if (selected[0] != 0) {*/
            if (!(nameVar.equals(""))) {
            Vector vector = null;
            if (jCheckBox1.isSelected() && isDouble(textAngolo.getText()) && isDouble(textForza.getText())) {
                vector = new Vector(nameVar, Double.parseDouble(textAngolo.getText()), Double.parseDouble(textForza.getText()));
                vectors.add(vector);
            } else if(isDouble(textX1.getText()) && isDouble(textY1.getText())){
                vector = new Vector(Double.parseDouble(textX1.getText()), Double.parseDouble(textY1.getText()), nameVar);
                vectors.add(vector);
            }
            if(vector != null){
                vectorList.setModel(new javax.swing.AbstractListModel<String>() {

                    String[] strings = addVectorNames();

                    public int getSize() {
                        return strings.length;
                    }

                    public String getElementAt(int i) {
                        return strings[i];
                    }
                });
                vectorsScrollPane.setViewportView(vectorList);
                allVisible();
                createButton.setVisible(false);
                textX1.setText(vector.x + "");
                textY1.setText(vector.y + "");
                textForza.setText(vector.forza + "");
                textAngolo.setText(vector.angolo + "");
                jCheckBox1.setEnabled(true);
                xRis += vector.x;
                yRis += vector.y;
                fRis = new Vector(xRis, yRis, "forza risultante");
                vectors.set(0, fRis);
                repaint();
            }
        }
        

    }//GEN-LAST:event_createButtonActionPerformed

    private void vectorListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vectorListKeyPressed

    }//GEN-LAST:event_vectorListKeyPressed

    private void vectorListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vectorListMouseClicked
        int[] selectedVectors = vectorList.getSelectedIndices();
        if (selectedVectors.length == 1) {
            textX1.setText(String.valueOf(vectors.get(selectedVectors[0]).x));
            textY1.setText(String.valueOf(vectors.get(selectedVectors[0]).y));
            textForza.setText(String.valueOf(vectors.get(selectedVectors[0]).forza));
            textAngolo.setText(String.valueOf(vectors.get(selectedVectors[0]).angolo));
            textName.setText(vectors.get(selectedVectors[0]).name);
        }
    }//GEN-LAST:event_vectorListMouseClicked

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed
    int x;
    int y;
    int finalX;
    int finalY;
    int num = 0;
    boolean drag = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed
    
    private void updateList() {
        vectorList.setModel(new javax.swing.AbstractListModel<String>() {

            String[] strings = addVectorNames();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        vectorsScrollPane.setViewportView(vectorList);
        xRis = 0;
        yRis = 0;
        for (int i = 1; i < vectors.size(); i++) {
            xRis += vectors.get(i).x;
            yRis += vectors.get(i).y;
        }
        fRis = new Vector(xRis, yRis, "forza risultante");
        vectors.set(0, fRis);
        repaint();
    }
    private void canvasPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasPanelMouseReleased
        finalX = evt.getX() - x;
        finalY = evt.getY() - y;
        Vector vector = new Vector(finalX, finalY, "drawVector" + num);
        
        vectors.add(vector);
        updateList();
        allVisible();
        vectorInputPanel.updateUI();
        textX1.setText(vector.x + "");
        textY1.setText(vector.y + "");
        textForza.setText(vector.forza + "");
        textAngolo.setText(vector.angolo + "");
        textName.setText("drawVector" + num);
        num += 1;
        jCheckBox1.setEnabled(true);
        if(!firstVec){
            xRis += vector.x;
            yRis += vector.y;
        }
        firstVec = false;
        fRis = new Vector(xRis, yRis, "forza risultante");
        vectors.set(0, fRis);
        drag = false;
        
        repaint();
    }//GEN-LAST:event_canvasPanelMouseReleased
    
    private void canvasPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasPanelMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_canvasPanelMousePressed

    private void canvasPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasPanelMouseDragged
        finalX = evt.getX();
        finalY = evt.getY();
        vectorTemp = new Vector(finalX, finalY, "vettoreTemporaneoXMouseDragged");
        drag = true;
        repaint();
        //repaint(finalX, finalY, 0, 0);
    }//GEN-LAST:event_canvasPanelMouseDragged

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        allInvisible();
        setEmptyText();
        repaint();
        jCheckBox1.setEnabled(true);
        backButton.setVisible(false);
        createButton.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        timer.stop();
        xObject = xCenter;
        yObject = yCenter;
        repaint();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed

        timer.stop();
        repaint();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        ActionListener act;
        act = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                xObject += xRis / 150;
                yObject += yRis / 150;
                repaint();
            }
        };
        timer = new Timer(1, act);
        timer.start(); 
        animationStarted = true;
    }//GEN-LAST:event_startButtonActionPerformed

    private void buttonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColorActionPerformed
        int[] selected = vectorList.getSelectedIndices();
        if (selected.length == 1) {
            Color newColor = JColorChooser.showDialog(null, "Choose a color", Color.BLUE);
            vectors.get(selected[0]-1).colore = newColor;
            repaint();
        }
    }//GEN-LAST:event_buttonColorActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed

        int[] selected = vectorList.getSelectedIndices();
        if (selected == null || selected.length == 0) {
            return;
        }
        if (selected[0] != 0 && vectors.size() - selected.length > 1) {
            for (int i = 0; i < selected.length; i++) {
                vectors.remove(selected[i]);
            }
        }
        updateList();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        for (int i = 0; i < vectors.size(); i++) {
            Vector vector = vectors.get(i);
            try{
                saveState(vector);
            }catch(IOException e){
                Path fileName = Path.of("vectors.txt");
                System.out.println(fileName);
            }
        }   
    }//GEN-LAST:event_saveButtonActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) 
        {
        File selectedFile = fileChooser.getSelectedFile();
        System.out.println(selectedFile.getName());
        try{
            importFile(selectedFile);
        }catch(IOException e){
            System.out.println("IOException");
        }
        
        }
        
    }//GEN-LAST:event_importButtonActionPerformed

    private void controlsPanelAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_controlsPanelAncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_controlsPanelAncestorResized

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized
        xCenter = (canvasPanel.getX() + canvasPanel.getWidth()) / 2;
        yCenter = (canvasPanel.getY() + canvasPanel.getHeight()) / 2;
        xObject = xCenter;
        yObject = yCenter;
        repaint();
    }//GEN-LAST:event_formAncestorResized

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if(!animationStarted){
            xCenter = (canvasPanel.getX() + canvasPanel.getWidth()) / 2;
            yCenter = (canvasPanel.getY() + canvasPanel.getHeight()) / 2;
            xObject = xCenter;
            yObject = yCenter;
        }
        repaint();
    }//GEN-LAST:event_formComponentResized

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
       int[] selected = vectorList.getSelectedIndices();
        if (selected[0] != 0 && selected.length == 1 && isDouble(textAngolo.getText()) &&
                isDouble(textForza.getText()) && isDouble(textX1.getText()) &&
                isDouble(textY1.getText()) && textName.getText() != null) {
            double oldAngolo = vectors.get(selected[0]).angolo;
            double oldForza = vectors.get(selected[0]).forza;
            double oldX = vectors.get(selected[0]).x;
            double oldY = vectors.get(selected[0]).y;
            String oldName = vectors.get(selected[0]).name;
            double newAngolo = Double.parseDouble(textAngolo.getText());
            double newForza = Double.parseDouble(textAngolo.getText());
            double newX = Double.parseDouble(textAngolo.getText());
            double newY = Double.parseDouble(textAngolo.getText());
            String newName = textAngolo.getText();
                if(oldAngolo != newAngolo ){
                    
                }
            vectors.get(selected[0]).y = Double.parseDouble(textForza.getText());
            vectors.get(selected[0]).x = Double.parseDouble(textX1.getText());
            vectors.get(selected[0]).forza = Double.parseDouble(textY1.getText());
            vectors.get(selected[0]).name = textName.getText();
        }
        repaint();
    }//GEN-LAST:event_applyButtonActionPerformed

    private void textNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textNamePropertyChange
        
    }//GEN-LAST:event_textNamePropertyChange

    private void textAngoloPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textAngoloPropertyChange
        
    }//GEN-LAST:event_textAngoloPropertyChange
    private void saveState(Vector vector)throws IOException{
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy.MM.dd HH.mm.ss");
        LocalDateTime now = LocalDateTime.now();
        String nameFile = "vectors" + dtf.format(now) + ".txt";
        Path fileName = Paths.get(nameFile);
        String text = vector.x +";"+ vector.y +";"+ vector.forza +";"+ vector.angolo +";" + vector.name +";" +xObject + ";"+ yObject + "\n";
        File myObj = new File("vectors" + dtf.format(now) + ".txt");
        myObj.createNewFile();
        Files.write(fileName,text.getBytes(), StandardOpenOption.APPEND);
        
        //String file_content = Files.readString(fileName);
    }
    private void importFile(File selectedFile) throws IOException {
        Path fileName = selectedFile.toPath();
        if(Files.exists(fileName) && Files.isReadable(fileName)){
            List<String> lines = Files.readAllLines(fileName);
            vectors.clear();
            for (String line : lines) 
            { 
                String[] parts = line.split(";");
                Vector vector = new Vector(Double.parseDouble(parts[0]), Double.parseDouble(parts[1]), parts[4]);
                xObject = Double.parseDouble(parts[5]);
                xObject = Double.parseDouble(parts[6]);
                vectors.add(vector);
            }
            updateList();
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacciaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacciaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacciaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacciaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacciaGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel angoloLabel;
    private javax.swing.JButton applyButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton buttonColor;
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel forzaLabel;
    private javax.swing.JButton importButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton newVectorButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JTextField textAngolo;
    private javax.swing.JLabel textColor;
    private javax.swing.JTextField textForza;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textX1;
    private javax.swing.JTextField textY1;
    private javax.swing.JPanel vectorInputPanel;
    private javax.swing.JList<String> vectorList;
    private javax.swing.JScrollPane vectorsScrollPane;
    private javax.swing.JLabel xCoordLabel;
    private javax.swing.JLabel yCoordLabel;
    // End of variables declaration//GEN-END:variables
}
